### PR TITLE
Overhaul of Guardsman Class System & Psychic Fun!

### PR DESCRIPTION
**Pull request by Sundowner8**
This completely overhauls the current Guardsman Class System to make each selection at least semi-unique
- Standard Guardsman are your regular rank-and-file cannon fodder
- Field Chiurgeon is the medic of the Imperial Guard, they start with two medi-packs, stimulants, and a medical HUD
- Sharpshooter starts with a long-las (I couldn't really think of much to give them)
- Scout start with a Stubber Pistol & Guardsman Sword
- Shock Guardsman start with an autogun & extra ammunition
- Heavy Weapons Specialist starts with full reinforced armor and a Heavy Stubber + extra ammunition

PSYCHIC FUN!
Primaris Psykers are sanctioned psykers that work within (usually) the Astra Militarum, they start with psychic powers (including TK) and no armor, only robes, they wield a Psyker Staff (renamed Wizard Staff) and are generally not great at fighting alone, their spawn point is in the Ecclesiarchy Church

OTHER STUFF
I've moved Psychic Powers to their own folder and renamed librarians.dm into psychic_powers.dm, as to make it more universal, renamed every prior type path with the new one, and gave Librarians TK.

That's all.

### CODE REVIEW

**Comment by Doosteroni** [comment]
>gave Librarians TK. 

Librarians are already very stronk, and two things. This is very powercreepy and maybe sharpshooter and scout should be merged.

Also I like Chiurgeon

**Comment by Doosteroni** [comment]
Especially Heavy specialist, they are especially strong

**Comment by Sundowner8** [comment]
That's the point, it gives the station more of a chance to fight against RTD memes without people having to RTD themselves to kill the problem (i.e Tyranids, Orks, Chaos Marines who go gung-ho, etc), the Guardsman in lore aren't a forced to be messed with even if they are cannon-fodder.

**Comment by Doosteroni** [comment]
Fair enough, But it seems to nullify any of the other roles

**Comment by Sundowner8** [comment]
What do you mean? If you are talking about Heavy Weapons Specialist, the Heavy Stubber fires very slow as a counter to its high damage, if you try to pick off a mobile target, it most likely won't even hit.

**Comment by Doosteroni** [comment]
Does the medic also have a lasgun? 'Cause that is a easy straight upgrade. That's about it

**Comment by Sundowner8** [comment]
Nope, they don't start with a lasgun, you can always get one from the barracks vending machine, it dispenses lasguns.

**Comment by Sundowner8** [comment]
Forgot to mention, there can only be ONE Primaris Psyker within a round, the open positions are limited to 1, for obvious reasons.

**Comment by Doosteroni** [comment]
Right then, sounds good!

**Comment by Daelso** [comment]
Have you tested all of this and confirm it works/compiles? Code looks good but that doesnt always mean yes lmao

**Comment by Sundowner8** [comment]
I have, I've tested every guardsman class and Primaris Psyker, it all works as intended, only thing I haven't tested is TK with Librarians but looking at it code-wise that should work fine too (it works as intended on Primaris Psykers so it shouldn't be any different there)

**Pull request merged**
