### PR TITLE
Librarians

### PR DESCRIPTION
**Pull request by PotatoTheDeveloper**
LIBRARIANS FUCKING YES, if it has a conflict its cuz i cant merge all the updates and changes from yesterday.

-Librarian specialization for ravenguard, salamanders and smurfs
-They have for now only 4 spells i will try to add more
-No i didnt make any changes for the rubrics(ksons) im planning to make changes to them in the future

### CODE REVIEW

**Comment by Doosteroni** [comment]
POGGERS

Merge conflikt

**Comment by PotatoTheDeveloper** [comment]
fucking goosecode.int, that thing is inevitable, and the ravenguard and salamander ones i think is the change of health that wel made for the techmarines

**Comment by Doosteroni** [comment]
quick! Fix da shit so we can speeeeeeeeeedmerge

**Comment by PotatoTheDeveloper** [comment]
RESOLVED!

**Comment by Doosteroni** [comment]
pog

**Pull request merged**
