### PR TITLE
Buff Robo Limbs

### PR DESCRIPTION
**Pull request by dabamman**
Their entire point in fluff is to be better than flesh, this makes it real.

### CODE REVIEW

**Comment by Doosteroni** [comment]
Looool no

**Comment by Doosteroni** [comment]
Anyone with a mechadentrite can aug, that’s super powercreepy

**Comment by Willowowowo** [comment]
They're already better than normal limbs in that they're incredibly easy to self repair compared to a normal limb

**Comment by dabamman** [comment]
Yeah but you die at the same rate since knockdown or crit and yah die, I dunno I did increase it by a lot prolly too much

**Comment by Daelso** [comment]
This seems kinda OP and way too buffed

**Comment by dabamman** [comment]
After some testing, the buff is not what was expected. The medium being shot by a las rifle it went up by 3 shots depending on which body part was hit. The values look large but do not translate to actual gameplay. The power creep would be in who actually gets the ability to surgically augment. Which can be removed from the surgical mechadendrite and force the actual Acolyte to physically modify each and every priest on the station.

**Comment by Daelso** [comment]
im gunna soft go with this and we'll see how OP this is lmao

**Pull request merged**
