### PR TITLE
Give all Non-Imperial factions their own radio freq

### PR DESCRIPTION
**Pull request by Sundowner8**
Something that should've been done in the first place.

### CODE REVIEW

**Comment by Sundowner8** [comment]
Also, I checked to see if these were all valid radio ranges before setting them, they should all be valid radio ranges.

**Comment by Doosteroni** [comment]
Will this remove their ability to listen to 144.1?

**Comment by Sundowner8** [comment]
@Doosteroni Yes, they'd have to switch to that frequency with their headset or use a Vox Caster set to that frequency to listen in, 1441 is actually the frequency for Death Squads so it's not a freq you can normally listen into like command, security, engineering etc.

**Comment by Doosteroni** [comment]
Does this work in reverse, where loyalists can listen in on nonloyalist frequencies? I’m not well versed on radios

**Comment by Sundowner8** [comment]
Yes, you can change your radio frequency through the headset menu, all you do is take your headset off & click on it, then you can change frequency
image

**Comment by Doosteroni** [comment]
I was more wondering if this would require encryption keys, so IG or someone can’t listen in.

**Comment by Sundowner8** [comment]
Nope
I don't know if Encryption Keys actually encrypt comms, they add an easy way for you to tune in on a freq.

**Comment by Doosteroni** [comment]
I believe without an encryption key you cannot listen to other frequencies.

**Comment by Doosteroni** [comment]
Since these frequencies don’t have encryption keys, you probably would be able to listen in.

**Comment by Sundowner8** [comment]
Yeah, for now it's better than every faction sharing the same frequency

**Pull request merged**
