### PR TITLE
Map Changes

### PR DESCRIPTION
**Pull request by PotatoTheDeveloper**
ehhhhhhhh some map changes for the space marines and a minor fix.

- Salamanders and Ultramarines have shields now! (also ravenguard gets one extra shield)
- Salamanders have a heavy plasma rifle like the other two SM chapters
- Minor fix in the map, some misplaced turf
- Baneblade is sealed
- The space marines chainswords are now in racks instead of tables

### CODE REVIEW

**Comment by Doosteroni** [comment]
mmmmm downthumb
 
me no like Sheild changes (it seems very selfish with the plasma stuff aswell)
But hey you can atomize some of that stuff and I think it would be perfect

**Comment by Willowowowo** [comment]
If all the marines are gonna get the same stuff, then they should just be turned into one chapter.

**Comment by PotatoTheDeveloper** [comment]
when i said everything is going to be added? lorewise every chapter has shields, for their champions

**Comment by Doosteroni** [comment]
hmm yes, that would make the most sense. Anyways, the problem with this PR is that salamanders are meant to be specialized, and you are trying to generalize them, while they keep their very solid flamers. I would be fine with RG losing plasma weapons (except maybe the pistol,) but only RG and SOB have shields, and I do not support handing those out like candy, seeing as sheilds are one of the most frustrating mechanics

**Comment by PotatoTheDeveloper** [comment]
also the heavy plasma rifle literally only the salamanders dont have one

**Comment by Doosteroni** [comment]
I am fine with giving just the UMs heavy plasma, but salamanders already enough
Again, you ARE a Salamanders player, let's make that clear,

**Comment by PotatoTheDeveloper** [comment]
me being a salamander does nothing about my changes, i just wanted to make things fair for things that should be common

**Comment by Doosteroni** [comment]
I still don't support this. I think plasma should be an UMs thing, and that salamanders already have enough things, they don't need more

**Comment by PotatoTheDeveloper** [comment]
maybe plasma for um only is right, but i dont know if the other two chapters would want the plasma weapons only for the um, i dont even use them

**Comment by Doosteroni** [comment]
UMs as they are currently don't have very many gimmicks, except for the dreadnought. If I am not mistaken they are also the least popular. RG are meant to be melee focused hit and run units, just as salamanders are meant to be torching everyone in sight. I don't like the shield change, seeing as salamanders use heavy flamers (which need 2 empty hands if I remember correctly). Atomize the Space marine changes, everything else looks good

**Comment by Daelso** [comment]
Unsure how I feel about this. Will think on it more before approving/denying

**Pull request closed without merging**
