### PR TITLE
Overhaul of Guardsman Class System

### PR DESCRIPTION
**Pull request by Sundowner8**
This completely overhauls the current Guardsman Class System to make each selection at least semi-unique

* Standard Guardsman are your regular rank-and-file cannon fodder
* Field Chiurgeon is the medic of the Imperial Guard, they start with two medi-packs, stimulants, and a medical HUD
* Sharpshooter starts with a long-las (I couldn't really think of much to give them)
* Scout start with a Stubber Pistol & Guardsman Sword
* Shock Guardsman start with an autogun & extra ammunition
* Heavy Weapons Specialist starts with full reinforced armor and a Heavy Stubber + extra ammunition

### CODE REVIEW

**Comment by Daelso** [comment]
Has this been tested? Last time I merged it, it broke hotkeys and a bunch of other stuff

**Comment by Doosteroni** [comment]
Why would anyone pick standard guard over a heavy or shock? And does heavy armor have slowdown or something

**Comment by Sundowner8** [comment]
> Has this been tested? Last time I merged it, it broke hotkeys and a bunch of other stuff

That's because the Psyker stuff was included in the update. I tested all the loadout options and they work fine.

**Comment by Sundowner8** [comment]
> Why would anyone pick standard guard over a heavy or shock? And does heavy armor have slowdown or something

Heavy Weapons Specialist is just the reinforced armor loadout option with a heavy stubber, the heavy stubber is very S L O W firing, but deals good damage, a problem with Shock is that autoguns run out of ammo quickly, so you could easily waste all your ammo on one ork, I don't think reinforced armor has a speed penalty or anything like that.

**Pull request merged**
