### PR TITLE
Krieg coats, Mechandrite recipe, Choppa waaaagh

### PR DESCRIPTION
**Pull request by Sancronis**
Krieg coats get cold protection equal to a winter coat; this is still inferior to a Valhallan greatcoat but means they won't freeze when they step off the shuttle.

### CODE REVIEW

**Comment by Sancronis** [comment]
First extra commit: Surgical mechandrites can now be made with syringe guns (sleepers were the only other appropriate exosuit module at the start that I could see) and the description for adding an autocannon mechandrite has been fixed to describe the module you actually need to add.

Second extra commit: When used on a conscious, living non-Ork, Ork choppas produce waaaagh. Normal choppas produce 5-10, stikks 5-15, big choppas and chain choppas 10-20. This doesn't apply to simple mobs such as rippers but works on non-humans like Tyranids.

**Comment by Sancronis** [comment]
PR now includes a map change that adds ammo for the missile launchers.
Old/New
Krieg have 4 fake missiles and 1 launcher in their armoury/Krieg have 4 krak missiles and 1 launcher in their armoury
Garrison have no missiles and 1 launcher in their armoury/Garrison have 3 krak missiles and 1 launcher in their armoury. There is also a crate in the vault (that needs to be opened by the RT) that contains a single plasma missile.
Ultramarines have 1 krak missile and 6 launchers in their armoury/Ultramarines have 8 krak missiles and 4 launchers in their armoury

**Comment by Daelso** [comment]
please make a PR for just the files you have edited

**Comment by Sancronis** [comment]
The included map file conflicts with the stuff that you recently added, hence the issue. Working on a fix now although restarted a couple times because of other edits. Or did you mean something else, sorry?

**Comment by Daelso** [comment]
ah didnt see you made map changes, sorry

**Comment by Sancronis** [comment]
So, that should work as it's a copy of the current map file (downloaded 50 minutes ago) with changes added in despite the branch being from a slightly earlier point. To preserve history, I could alternatively close the PR and add everything into a shiny new branch.

**Comment by Daelso** [comment]
that would probably be for the best

**Pull request closed without merging**
