### PR TITLE
Changes to Plague Marines

### PR DESCRIPTION
**Pull request by PotatoTheDeveloper**
Okay so my map merge simply isnt working properly so i want to ask somebody to add magazines for them in their ship and delete the free plague rifle in the racks

### **CHANGELOG**

- Plague Marines now have bolters and spawn with a plague bayonet to attach it in the bolter
- When they spawn they will choose between the plague rifle and bolter(the only way to infect with the bolter is the bayonet and it is melee)

### CODE REVIEW

**Comment by PotatoTheDeveloper** [comment]
the fuck?????
gun.dmi what

**Comment by Mocha-Not-Latte** [comment]
> the fuck?????
> gun.dmi what

[https://github.com/Daelso/Cadia-Station-40k/commit/d038f3391a39a221551c8c576a073fdb1e22299b](url)

**Comment by PotatoTheDeveloper** [comment]
url isnt working
but i would guess that there is a pr that modified the guns.dmi?

**Comment by Mocha-Not-Latte** [comment]
yeah commit d038f33

**Comment by PotatoTheDeveloper** [comment]
alright one second im closing and updating so i can resolve this

**Pull request closed without merging**
