### PR TITLE
goose murder

### PR DESCRIPTION
**Pull request by Valterak**
Here's a lotta stuff packaged together

- New sprites for laspistols and hellpistols, an inquisition variant for them and weapon racks to accomodate them
- Removed a lot of the geese references.
- Small update to acolyte lair.
- New sprites for the wooden floors, added a little more carpet to the bar
- Fixed that little bug where the acolytes weren't getting headsets

had a bit of a goof during commit so my preferences got updated oops vov

### CODE REVIEW

**Comment by Doosteroni** [comment]
You went too far man! Too far

**Comment by Valterak** [comment]
suffer not the geese to live.

**Comment by Doosteroni** [comment]
Well smart man, what will make us unique after the death Of geese? What will make this goosecode?

**Comment by MnemeThePsyker** [comment]
A most holy of purges. The Cult Mechanicus approves.

**Pull request merged**
