### PR TITLE
Reduce cure chance of Plague

### PR DESCRIPTION
**Pull request by Sundowner8**
The 50% cure chance is too harsh, it's easy to cure the Plague even without Viro, people who think you NEED viro to cure the Plague don't know how to actually cure it.

### CODE REVIEW

**Comment by Doosteroni** [comment]
Wait, so is the cure chance 50% per tick? Cause that is straight busted yo

**Comment by Sundowner8** [comment]
@Doosteroni 50% cure chance per reagent amount I believe, I don't know why they were nerfed in such a way.
There will always be people complaining about the Plague & Plague Marines in general just like they do with 1ksons, nids, and others, even if you do nerf them this won't please them, nerfing them in busted ways won't help either.

**Comment by Doosteroni** [comment]
Right, I see no problems with this. the main problem I gave with PM is the fact they don't fucking die. But then again kraks exist so whateva

**Comment by Sundowner8** [comment]
Many things can kill a Plague Marine, such as:
Chainswords
Concentrated Hellgun fire
Kraks
Rocket Launchers
Multiple frag grenades
And lots of other things, you can easily kill a single Plague Marine if the station/guard work together to get it done.
Also with the Guardsman Overhaul getting merged again soon(tm) the station will have more of a chance.

**Comment by Doosteroni** [comment]
_Working together?_ 

The thing about PM is that usually in a one-on-one with Astartes they will win just due to the fact they are _better_ and will probably be able to incapacitate you before you can get them down

**Comment by Daelso** [comment]
until this becomes an issue, not gunna change it back. people still getting yeeted nonstop by plague

**Pull request closed without merging**
